Update README
discordjs-japan/om-syrinx pull request #24
Opened 2024-05-19 23:36 UTC by femshima

2024-05-20 06:15 UTC, cm-ayf commented on README.md
> +om-syrinx（読み方：おーむ・しーりんくす）は，読み上げボット「[om](https://github.com/discordjs-japan/om)」のために作られた，音声合成ライブラリです．
```suggestion
om-syrinx（読み方：おーむ・しーりんくす）は，Discordの読み上げボット「[om](https://github.com/discordjs-japan/om)」のために作られた，音声合成ライブラリです．
```

2024-05-22 06:02 UTC, Mogyuchi commented on README.md
> `tar xz`等で展開して，hogeフォルダができることを確認します．

hogeフォルダを適当な場所に配置します. の方が良いのではないだろうか

2024-05-22 06:25 UTC, Mogyuchi requested changes

2024-05-22 06:25 UTC, Mogyuchi commented on README.md
> +ここでは，[`htsvoice-tohoku-f01`](https://github.com/icn-lab/htsvoice-tohoku-f01)をダウンロードします．`htsvoice-tohoku-f01`は，4種類の声色のモデルを含むレポジトリです．他のモデルを利用することもできます．
```suggestion
ここでは，[`htsvoice-tohoku-f01`](https://github.com/icn-lab/htsvoice-tohoku-f01)をダウンロードします．`htsvoice-tohoku-f01`は，4種類の声色のモデルを含むリポジトリです．他のモデルを利用することもできます．
```
呼称統一。

2024-05-22 06:54 UTC, Mogyuchi requested changes

2024-05-22 06:54 UTC, Mogyuchi commented on README.md
> +ここでは，[`htsvoice-tohoku-f01`](https://github.com/icn-lab/htsvoice-tohoku-f01)をダウンロードします．`htsvoice-tohoku-f01`は，4種類の声色のモデルを含むリポジトリです．他のモデルを利用することもできます．
```suggestion
ここでは例として，[`htsvoice-tohoku-f01`](https://github.com/icn-lab/htsvoice-tohoku-f01)を利用します．`htsvoice-tohoku-f01`は，4種類の声色のモデルを含むリポジトリです．他のモデルを利用することもできます．
```

2024-05-22 08:33 UTC, Mogyuchi requested changes

2024-05-22 08:33 UTC, Mogyuchi commented on README.md
> +実際のテキスト処理と音声合成はそれぞれ「[jpreprocess](https://crates.io/crates/jpreprocess)」と「[jbonsai](https://crates.io/crates/jbonsai)」が担っています．このリポジトリはこれらとNode.jsとのバインディングに加え，スレッド管理，バッファリング，opusへのエンコード機能を提供します．
```suggestion
実際のテキスト処理と音声合成はそれぞれ「[jpreprocess](https://crates.io/crates/jpreprocess)」と「[jbonsai](https://crates.io/crates/jbonsai)」が担っています．このライブラリはこれらとNode.jsとのバインディングに加え，スレッド管理，バッファリング，opusへのエンコード機能を提供します．
```

2024-05-22 08:35 UTC, cm-ayf commented on README.md
> +実際のテキスト処理と音声合成はそれぞれ「[jpreprocess](https://crates.io/crates/jpreprocess)」と「[jbonsai](https://crates.io/crates/jbonsai)」が担っています．このリポジトリはこれらとNode.jsとのバインディングに加え，スレッド管理，バッファリング，opusへのエンコード機能を提供します．
それならom-syrinxって言う

2024-05-22 11:05 UTC, Mogyuchi approved these changes

2024-05-22 12:40 UTC, Mogyuchi approved these changes

2024-05-22 12:53 UTC, Mogyuchi commented on README.md
> +  htsvoice-tohoku-f01 の`master`ブランチ (<https://github.com/icn-lab/htsvoice-tohoku-f01/archive/refs/heads/master.tar.gz>) をダウンロードし，カレントディレクトリに解凍してください．
```suggestion
  [htsvoice-tohoku-f01](https://github.com/icn-lab/htsvoice-tohoku-f01) の`master`ブランチ (<https://github.com/icn-lab/htsvoice-tohoku-f01/archive/refs/heads/master.tar.gz>) をダウンロードし，カレントディレクトリに解凍してください．
```

2024-05-22 12:53 UTC, Mogyuchi commented on README.md
> +  ここでは例として，[htsvoice-tohoku-f01](https://github.com/icn-lab/htsvoice-tohoku-f01) を使用しました．htsvoice-tohoku-f01 は，4つの`.htsvoice`モデルを含むリポジトリです．他の`.htsvoice`モデルを使用することもできます．
```suggestion
  ここでは例として，htsvoice-tohoku-f01 を使用しました．htsvoice-tohoku-f01 は，4つの`.htsvoice`モデルを含むリポジトリです．他の`.htsvoice`モデルを使用することもできます．
```

2024-05-22 12:56 UTC, Mogyuchi commented on README.md
> +  [jpreprocessの最新のリリース](https://github.com/jpreprocess/jpreprocess/releases/latest)から辞書 (`naist-jdic-jpreprocess.tar.gz`) をダウンロードし，カレントディレクトリに解凍してください．
```suggestion
  [jpreprocessの最新のリリース](https://github.com/jpreprocess/jpreprocess/releases/latest)から[辞書 (`naist-jdic-jpreprocess.tar.gz`)](https://github.com/jpreprocess/jpreprocess/releases/latest/download/naist-jdic-jpreprocess.tar.gz) をダウンロードし，カレントディレクトリに解凍してください．
```

2024-05-22 13:10 UTC, merged

2024-05-24 13:38 UTC, Mogyuchi approved these changes